

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
//import Header from "@/components/Header"; 
//import Footer from "@/components/Footer"; 
//import { useAuthStore } from "@/store/authStore"; 
//import ClientLayout from "./(dashboard)/ClientLayout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "TechMart - Your One-Stop Online Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  //const user = useAuthStore((state) => state.user);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/*         
        {user && <Header />}
        <main> {children} </main>
        {user && <Footer />} */}

        
          {children}
   
      </body>
    </html>
  );
}